{{/* boolean feature tags */}}
{{- $docker := true -}}{{/* true if this machine should have Docker installed */}}
{{- $ephemeral := false -}}{{/* true if this machine is ephemeral, e.g. a cloud or VM instance */}}
{{- $headless := false -}}{{/* true if this machine does not have a screen and keyboard */}}
{{- $isovalent := true -}}{{/* true if this machine should have Isovalent secrets from 1Password */}}
{{- $kubernetes := false -}}{{/* true if this machine is used for Kubernetes work */}}
{{- $personal := false -}}{{/* true if this machine should have personal secrets from LastPass */}}
{{- "" -}}

{{- $email := "" -}}
{{- if hasKey . "email" -}}
{{-   $email = .email -}}
{{- else -}}
{{-   $email = promptString "email" -}}
{{- end -}}

{{- $osID := .chezmoi.os -}}
{{- if hasKey .chezmoi.osRelease "id" -}}
{{-   $osID = printf "%s-%s" .chezmoi.os .chezmoi.osRelease.id -}}
{{- end -}}

{{/* detect GitHub codespaces, VSCode remote containers, Docker containers, Multipass VMs, and Vagrant boxes */}}
{{- if or (env "CODESPACES") (env "REMOTE_CONTAINERS_IPC") (eq .chezmoi.username "root" "ubuntu" "vagrant" "vscode") -}}
{{-   $ephemeral = true -}}
{{-   $headless = true -}}
{{- end -}}

{{- if eq .chezmoi.os "windows" -}}
{{-   $ephemeral = true -}}
{{- end -}}

[data]
    docker = {{ $docker }}
    ephemeral = {{ $ephemeral }}
    headless = {{ $headless }}
    isovalent = {{ $isovalent }}
    kubernetes = {{ $kubernetes }}
    personal = {{ $personal }}
    osid = {{ $osID | quote }}
    email = {{ $email | quote }}
[onepassword]
    command = "op"
