[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
    stripComponents = 1

[".zsh/fzf-theme.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/fnune/base16-fzf/master/bash/base16-gruvbox-dark-hard.config"

[".zsh/spaceship-theme.zsh"]
    type = "git-repo"
    url = "https://github.com/spaceship-prompt/spaceship-prompt.git"
    refreshPeriod = "168h"
    
[".local/share/nvim/site/pack/nvim-lspconfig/opt/nvim-lspconfig"]
    type = "git-repo"
    url = "https://github.com/neovim/nvim-lspconfig.git"
    refreshPeriod = "168h"
    
[".config/nvim"]
    type = "git-repo"
    refreshPeriod = "168h"
    url = "https://github.com/AstroNvim/AstroNvim.git"
    exclude = ["nvim/lua/user"]